# Generated by Django 4.2.4 on 2023-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_number',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер изображения'),
        ),
    ]
